// Generated by CoffeeScript 1.9.1
var Utils;

Utils = {
  lighterColor: function(rbg) {
    return {
      r: Math.min(255, rgb.r * 1.2),
      g: Math.min(255, rgb.g * 1.2),
      b: Math.min(255, rgb.b * 1.2)
    };
  },
  darkerColor: function(rbg) {
    return {
      r: rgb.r * .8,
      g: rgb.g * .8,
      b: rgb.b * .8
    };
  },
  ImageResource: function(src, onload) {
    var img;
    img = new Image;
    img.onload = onload(img);
    img.src = src;
    return img;
  },
  SoundResource: function(src, onload) {
    var snd;
    snd = new Audio;
    snd.preload = "auto";
    snd.oncanplaythrough = onload(snd);
    snd.src = src;
    return snd;
  }
};
